from subprocess import check_call


def dipy_dti(input_files, bval, bvec, mask, outdir):
    """
    Setup DIPY dipy_fit_DTI command.

    Parameters
    ----------
    input_files : str
        Path to dwi image.
    bval : str
        Path to bval image.
    bvec : str
        Path to bvec image.
    mask: str
        Path to mask image.
    outdir: str
        Output path.

    Returns
    -------
    Output files generated by dipy_fit_DTI in specified output directory .

    Examples
    --------
    Run dipy_fit_DTI on local data and save it to the Desktop.

    >>> dipy_dti('sub-01_desc-preproc_dwi.nii.gz',
                 'sub-01_desc-preproc_dwi.bval',
                 'sub-01_desc-preproc_dwi.bvec',
                 'sub-01_desc-brain_mask.nii.gz',
                 '/home/user/Desktop)
    """

    # create the command
    cmd = ["dipy_fit_dti", input_files, bval, bvec, mask,
           "--out_dir", outdir
           ]
    check_call(cmd)
    return


def dipy_bep16(bids_dir, subject_label, session=None):
    """
    Restructure DIPY outcomes following BIDS BEP16 conventions.

    Parameters
    ----------
    bids_dir : str
        Path to BIDS root directory.
    subject_label : str
        Label of subject to move (without 'sub-').
    session : str, optional
        If multiple sessions exist, create session specific
        structure.
    """
