name: deploy-docs

on:
  push:
    branches:
    - main

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: s-weigand/setup-conda@v1
      with:
        activate-conda: false


    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements-dev.txt
    - name: Install mrtrix
      run: |
        conda install -c mrtrix3 mrtrix3
    - name: Install bids_bep16_conv
      run: |
        pip install ./
    - name: Build the docs
      run: |
        cd docs && make clean html
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html
        commit_message: ${{ github.event.head_commit.message }}
